//! Generate Lean4 soundness proof files for SEC rule candidates.
//!
//! Each candidate rule gets a `Sound_<hash>.lean` file with a theorem
//! proving its soundness. The tactic is selected by RuleKind.
//! NO SORRY EVER — if Lean rejects the proof, the rule is discarded.

use kernel_types::hash;

use super::rule_syn::{RuleSyn, RuleKind, RuleExpr};

/// Generate a Lean4 soundness proof file for a candidate rule.
///
/// Returns the file name and file content.
/// The generated theorem uses tactics appropriate to the rule kind.
pub fn generate_soundness_file(rule: &RuleSyn) -> (String, String) {
    let rule_hash = rule.rule_hash();
    let hash_hex = hash::hex(&rule_hash);
    let short_hash = &hash_hex[..16];
    let file_name = format!("Sound_{}.lean", short_hash);
    let theorem_name = format!("sound_{}", short_hash);

    let mut lines = Vec::new();

    // Header
    lines.push("/-!".to_string());
    lines.push(format!(
        "  SEC Soundness Proof for rule: {}",
        rule.description
    ));
    lines.push(format!("  Kind: {:?}", rule.kind));
    lines.push(format!("  Arity: {}", rule.arity));
    lines.push(format!("  Hash: {}", hash_hex));
    lines.push("  Generated by SEC engine — all proofs must be complete.".to_string());
    lines.push("-/".to_string());
    lines.push(String::new());

    // Imports
    lines.push("import KernelVm.InvSyn".to_string());
    lines.push("import KernelVm.SEC.RuleSyn".to_string());
    lines.push(String::new());

    // Namespace
    lines.push("namespace KernelVm.SEC".to_string());
    lines.push(String::new());

    // Generate the theorem
    let (stmt, tactic) = generate_theorem_body(rule);

    lines.push(format!("/-- Soundness of SEC rule: {} -/", rule.description));
    lines.push(format!("theorem {} :", theorem_name));
    lines.push(format!("    {} := by", stmt));
    lines.push(format!("  {}", tactic));
    lines.push(String::new());
    lines.push("end KernelVm.SEC".to_string());
    lines.push(String::new());

    (file_name, lines.join("\n"))
}

/// Generate the theorem statement and tactic for a rule.
fn generate_theorem_body(rule: &RuleSyn) -> (String, String) {
    let stmt = generate_theorem_statement(rule);
    let tactic = select_tactic(&rule.kind);
    (stmt, tactic)
}

/// Generate the theorem statement from the rule's structure.
fn generate_theorem_statement(rule: &RuleSyn) -> String {
    // Universal quantification over metavariables
    let mut quantifiers = String::new();
    for i in 0..rule.arity {
        quantifiers.push_str(&format!("(e{} : KernelVm.InvSyn.Expr) ", i));
    }

    // Premises as hypotheses
    let premises_str = if rule.premises.is_empty() {
        String::new()
    } else {
        let prem_strs: Vec<String> = rule.premises.iter().enumerate().map(|(i, p)| {
            format!("(h{} : {})", i, rule_expr_to_lean(p))
        }).collect();
        prem_strs.join(" ") + " → "
    };

    // Conclusion
    let conclusion = rule_expr_to_lean(&rule.conclusion);

    if rule.premises.is_empty() {
        format!("∀ {}{}", quantifiers, conclusion)
    } else {
        format!("∀ {}{}{}", quantifiers, premises_str, conclusion)
    }
}

/// Convert a RuleExpr to a Lean4 expression string.
fn rule_expr_to_lean(expr: &RuleExpr) -> String {
    match expr {
        RuleExpr::MetaVar(i) => format!("e{}", i),
        RuleExpr::Concrete(e) => e.to_lean(),
        RuleExpr::StepPreserved(inner, delta) => {
            format!("SEC.stepPreserved ({}) {}", rule_expr_to_lean(inner), delta)
        }
        RuleExpr::LinkImplies(a, b) => {
            format!("SEC.linkImplies ({}) ({})", rule_expr_to_lean(a), rule_expr_to_lean(b))
        }
        RuleExpr::And(a, b) => {
            format!("({} ∧ {})", rule_expr_to_lean(a), rule_expr_to_lean(b))
        }
        RuleExpr::Or(a, b) => {
            format!("({} ∨ {})", rule_expr_to_lean(a), rule_expr_to_lean(b))
        }
        RuleExpr::Le(a, b) => {
            format!("({} ≤ {})", rule_expr_to_lean(a), rule_expr_to_lean(b))
        }
        RuleExpr::AddDelta(inner, delta) => {
            format!("({} + {})", rule_expr_to_lean(inner), delta)
        }
    }
}

/// Select the appropriate Lean4 tactic based on the rule kind.
fn select_tactic(kind: &RuleKind) -> String {
    match kind {
        RuleKind::StepPreservation => "omega <;> simp".to_string(),
        RuleKind::Monotonicity => "intro n; omega".to_string(),
        RuleKind::InequalityLift => "intro n; linarith".to_string(),
        RuleKind::AlgebraicIdentity => "ring_nf; norm_num".to_string(),
        RuleKind::Composition => "intro n; tauto".to_string(),
        RuleKind::Rewrite => "intro n; simp_all".to_string(),
    }
}

/// Get the theorem name for a rule (used by other modules to reference it).
pub fn theorem_name_for_rule(rule: &RuleSyn) -> String {
    let rule_hash = rule.rule_hash();
    let hash_hex = hash::hex(&rule_hash);
    let short_hash = &hash_hex[..16];
    format!("sound_{}", short_hash)
}

/// Get the file name for a rule's soundness proof.
pub fn file_name_for_rule(rule: &RuleSyn) -> String {
    let rule_hash = rule.rule_hash();
    let hash_hex = hash::hex(&rule_hash);
    let short_hash = &hash_hex[..16];
    format!("Sound_{}.lean", short_hash)
}

/// Get the import path for a rule's soundness proof.
pub fn import_for_rule(rule: &RuleSyn) -> String {
    let rule_hash = rule.rule_hash();
    let hash_hex = hash::hex(&rule_hash);
    let short_hash = &hash_hex[..16];
    format!("KernelVm.SEC.Sound_{}", short_hash)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_rule() -> RuleSyn {
        RuleSyn {
            kind: RuleKind::StepPreservation,
            arity: 1,
            premises: vec![RuleExpr::MetaVar(0)],
            conclusion: RuleExpr::StepPreserved(Box::new(RuleExpr::MetaVar(0)), 1),
            description: "ground expression preserved".to_string(),
            size: 2,
        }
    }

    #[test]
    fn generate_soundness_no_sorry() {
        let rule = make_test_rule();
        let (file_name, content) = generate_soundness_file(&rule);
        assert!(file_name.starts_with("Sound_"));
        assert!(file_name.ends_with(".lean"));
        assert!(!content.contains("sorry"), "Generated file must never contain sorry");
        assert!(content.contains("theorem sound_"));
        assert!(content.contains("import KernelVm.InvSyn"));
        assert!(content.contains("import KernelVm.SEC.RuleSyn"));
        assert!(content.contains("namespace KernelVm.SEC"));
    }

    #[test]
    fn generate_deterministic() {
        let rule = make_test_rule();
        let (n1, c1) = generate_soundness_file(&rule);
        let (n2, c2) = generate_soundness_file(&rule);
        assert_eq!(n1, n2);
        assert_eq!(c1, c2);
    }

    #[test]
    fn tactic_selection_by_kind() {
        assert!(select_tactic(&RuleKind::StepPreservation).contains("omega"));
        assert!(select_tactic(&RuleKind::Monotonicity).contains("omega"));
        assert!(select_tactic(&RuleKind::InequalityLift).contains("linarith"));
        assert!(select_tactic(&RuleKind::AlgebraicIdentity).contains("ring"));
        assert!(select_tactic(&RuleKind::Composition).contains("tauto"));
        assert!(select_tactic(&RuleKind::Rewrite).contains("simp"));
    }

    #[test]
    fn theorem_name_consistent() {
        let rule = make_test_rule();
        let name = theorem_name_for_rule(&rule);
        let (_, content) = generate_soundness_file(&rule);
        assert!(content.contains(&name));
    }

    #[test]
    fn import_path_format() {
        let rule = make_test_rule();
        let imp = import_for_rule(&rule);
        assert!(imp.starts_with("KernelVm.SEC.Sound_"));
    }

    #[test]
    fn rule_expr_to_lean_covers_all_variants() {
        // MetaVar
        assert_eq!(rule_expr_to_lean(&RuleExpr::MetaVar(0)), "e0");
        // Concrete
        let concrete = rule_expr_to_lean(&RuleExpr::Concrete(crate::invsyn::ast::Expr::Const(5)));
        assert!(concrete.contains("5"));
        // And
        let and_expr = rule_expr_to_lean(&RuleExpr::And(
            Box::new(RuleExpr::MetaVar(0)),
            Box::new(RuleExpr::MetaVar(1)),
        ));
        assert!(and_expr.contains("∧"));
        // Le
        let le_expr = rule_expr_to_lean(&RuleExpr::Le(
            Box::new(RuleExpr::MetaVar(0)),
            Box::new(RuleExpr::MetaVar(1)),
        ));
        assert!(le_expr.contains("≤"));
    }
}
