//! Proof checker — Lean oracle.
//!
//! Writes a .lean file with `theorem proof_N : <Prop> := by <tactics>`,
//! runs `lake build`, and returns Accept/Reject.
//!
//! Pattern reused from sec_engine.rs:verify_soundness_proof().
//! Defense in depth: sorry detection BEFORE lake build.

use std::path::Path;
use std::process::Command;
use std::time::Duration;
use kernel_types::{Hash32, hash};

use super::statement::ProofStatement;
use super::candidate::ProofCandidate;

/// Result of proof checking via Lean.
#[derive(Debug, Clone)]
pub enum ProofVerdict {
    /// Lean accepted the proof. Contains hash of the proof file.
    Accepted { proof_hash: Hash32 },
    /// Lean rejected the proof.
    Rejected { reason: String },
    /// Lean timed out.
    Timeout,
}

/// Check a proof candidate against a statement using the Lean type-checker.
///
/// 1. Generate .lean file content
/// 2. Sorry check (defense in depth)
/// 3. Write to lean/ProofEnum/<namespace>/Proof_<rank>.lean
/// 4. Run `lake build`
/// 5. Parse result
/// 6. Clean up on failure
pub fn check_proof(
    lean_dir: &str,
    statement: &ProofStatement,
    candidate: &ProofCandidate,
) -> ProofVerdict {
    let content = generate_lean_file(statement, candidate);

    // Defense in depth: reject if sorry is present
    if check_content_for_sorry(&content) {
        return ProofVerdict::Rejected {
            reason: "sorry detected in generated proof".into(),
        };
    }

    let lean_path = Path::new(lean_dir);

    // Build directory path from namespace (e.g., "ProofEnum.Goldbach" -> "ProofEnum/Goldbach")
    let ns_path = statement.namespace.replace('.', "/");
    let proof_dir = lean_path.join(&ns_path);

    // Ensure directory exists
    if std::fs::create_dir_all(&proof_dir).is_err() {
        return ProofVerdict::Rejected {
            reason: "failed to create proof directory".into(),
        };
    }

    // Write the proof file
    let file_name = format!("Proof_{}.lean", candidate.rank);
    let file_path = proof_dir.join(&file_name);
    if std::fs::write(&file_path, &content).is_err() {
        return ProofVerdict::Rejected {
            reason: "failed to write proof file".into(),
        };
    }

    // Run lake build with timeout
    let output = Command::new("lake")
        .arg("build")
        .current_dir(lean_path)
        .output();

    match output {
        Ok(out) => {
            if out.status.success() {
                let proof_hash = hash::H(content.as_bytes());
                ProofVerdict::Accepted { proof_hash }
            } else {
                // Clean up the failed file
                let _ = std::fs::remove_file(&file_path);
                let stderr = String::from_utf8_lossy(&out.stderr);
                ProofVerdict::Rejected {
                    reason: format!("lake build failed: {}", stderr),
                }
            }
        }
        Err(e) => {
            let _ = std::fs::remove_file(&file_path);
            ProofVerdict::Rejected {
                reason: format!("failed to run lake: {}", e),
            }
        }
    }
}

/// Generate a complete .lean file for a proof candidate.
pub fn generate_lean_file(statement: &ProofStatement, candidate: &ProofCandidate) -> String {
    let imports = if statement.lean_imports.is_empty() {
        String::new()
    } else {
        statement
            .lean_imports
            .iter()
            .map(|i| format!("import {}", i))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n"
    };

    let tactics = candidate.to_lean_tactics();
    let ns = &statement.namespace;
    let prop = &statement.lean_prop;

    format!(
        "-- Auto-generated by Universal Proof Enumerator (rank {})\n\
         -- DO NOT EDIT — this file is machine-verified.\n\
         {imports}\n\
         namespace {ns}\n\
         \n\
         theorem proof_{rank} : {prop} := by\n  \
         {tactics}\n\
         \n\
         end {ns}\n",
        candidate.rank,
        imports = imports,
        ns = ns,
        rank = candidate.rank,
        prop = prop,
        tactics = tactics,
    )
}

/// Check if content contains `sorry` as a standalone tactic word.
/// Mirrors sec_engine.rs:check_content_for_sorry().
fn check_content_for_sorry(content: &str) -> bool {
    for line in content.lines() {
        let trimmed = line.trim();
        // Skip comments
        if trimmed.starts_with("--") || trimmed.starts_with("/-") {
            continue;
        }
        // Check for sorry as a standalone word
        for (i, _) in trimmed.match_indices("sorry") {
            let before_ok = i == 0 || !trimmed.as_bytes()[i - 1].is_ascii_alphanumeric();
            let after_idx = i + 5;
            let after_ok =
                after_idx >= trimmed.len() || !trimmed.as_bytes()[after_idx].is_ascii_alphanumeric();
            if before_ok && after_ok {
                return true;
            }
        }
    }
    false
}

/// Timeout duration for lake build (5 minutes).
pub const LAKE_BUILD_TIMEOUT: Duration = Duration::from_secs(300);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proof_enum::statement::Difficulty;

    fn test_statement() -> ProofStatement {
        ProofStatement {
            id: "test_zfc".into(),
            lean_prop: "(0 : Nat) ≠ 1".into(),
            lean_imports: vec![],
            namespace: "ProofEnum.TestZFC".into(),
            description: "Test: 0 ≠ 1".into(),
            difficulty: Difficulty::Known,
        }
    }

    fn test_candidate(rank: u64) -> ProofCandidate {
        ProofCandidate {
            tactics: vec![
                crate::proof_enum::candidate::Tactic::Decide,
            ],
            rank,
        }
    }

    #[test]
    fn generate_lean_file_correct() {
        let stmt = test_statement();
        let cand = test_candidate(0);
        let content = generate_lean_file(&stmt, &cand);

        assert!(content.contains("theorem proof_0 : (0 : Nat) ≠ 1 := by"));
        assert!(content.contains("decide"));
        assert!(content.contains("namespace ProofEnum.TestZFC"));
        assert!(content.contains("end ProofEnum.TestZFC"));
    }

    #[test]
    fn generate_lean_file_with_imports() {
        let stmt = ProofStatement {
            id: "test_import".into(),
            lean_prop: "∀ n : Nat, True".into(),
            lean_imports: vec!["Mathlib.Data.Nat.Prime.Basic".into()],
            namespace: "ProofEnum.TestImport".into(),
            description: "Test with import".into(),
            difficulty: Difficulty::Known,
        };
        let cand = test_candidate(42);
        let content = generate_lean_file(&stmt, &cand);

        assert!(content.contains("import Mathlib.Data.Nat.Prime.Basic"));
        assert!(content.contains("theorem proof_42"));
    }

    #[test]
    fn sorry_detection_works() {
        assert!(check_content_for_sorry("  sorry"));
        assert!(check_content_for_sorry("theorem x := sorry"));
        assert!(!check_content_for_sorry("-- sorry in comment"));
        assert!(!check_content_for_sorry("/- sorry -/"));
        assert!(!check_content_for_sorry("notsorry"));
        assert!(!check_content_for_sorry("sorrynothing"));
    }

    #[test]
    fn sorry_detection_empty() {
        assert!(!check_content_for_sorry(""));
        assert!(!check_content_for_sorry("theorem x := by decide"));
    }
}
