import OpenProblems.Goldbach.Statement
import OpenProblems.Collatz.Statement
import OpenProblems.TwinPrimes.Statement
import OpenProblems.FLT.Statement
import OpenProblems.OddPerfect.Statement
import OpenProblems.Mersenne.Statement
import OpenProblems.ZFC.Statement
import OpenProblems.Mertens.Statement
import OpenProblems.Legendre.Statement
import OpenProblems.ErdosStraus.Statement
import OpenProblems.BSD.Statement
import OpenProblems.WeakGoldbach.Statement
import OpenProblems.Bertrand.Statement
import OpenProblems.Lagrange.Statement
-- IRC Invariant files
import OpenProblems.Goldbach.Invariant
import OpenProblems.Collatz.Invariant
import OpenProblems.TwinPrimes.Invariant
import OpenProblems.FLT.Invariant
import OpenProblems.OddPerfect.Invariant
import OpenProblems.Mersenne.Invariant
import OpenProblems.ZFC.Invariant
import OpenProblems.Mertens.Invariant
import OpenProblems.Legendre.Invariant
import OpenProblems.ErdosStraus.Invariant
import OpenProblems.BSD.Invariant
import OpenProblems.WeakGoldbach.Invariant
import OpenProblems.Bertrand.Invariant
import OpenProblems.Lagrange.Invariant
