-- ProofEnum: Universal Proof Enumerator library.
--
-- This module contains machine-verified proofs generated by the
-- Universal Proof Enumerator engine. Each theorem is a proof of
-- a mathematical proposition, verified by the Lean type-checker.
--
-- No sorry. No axiom. Every proof is constructive.

import ProofEnum.Registry
