import KernelVm.InvSyn

/-!
# Layer B: Polynomial Invariants

SOS (Sum of Squares) certificate verification and Positivstellensatz-based
decision procedure for polynomial inequalities over InvSyn expressions.

For polynomial invariants, the checker verifies:
1. The invariant expression uses only polynomial operations (add, sub, mul, pow)
2. The SOS certificate (if provided) verifies the polynomial identity
-/

namespace KernelVm.Layers.Polynomial

open KernelVm.InvSyn

/-- Check if an expression is in the polynomial fragment.
    Polynomial means: mul and pow are allowed, but no bounded quantifiers
    over non-polynomial bodies, no isPrime, no analytic operations. -/
def isPoly : Expr → Bool
  | .var _ => true
  | .const _ => true
  | .add l r => isPoly l && isPoly r
  | .sub l r => isPoly l && isPoly r
  | .mul l r => isPoly l && isPoly r
  | .neg e => isPoly e
  | .modE l r => isPoly l && isPoly r
  | .pow base _ => isPoly base
  | .le l r => isPoly l && isPoly r
  | .lt l r => isPoly l && isPoly r
  | .eq l r => isPoly l && isPoly r
  | .ne l r => isPoly l && isPoly r
  | .andE l r => isPoly l && isPoly r
  | .orE l r => isPoly l && isPoly r
  | .notE e => isPoly e
  | .implies l r => isPoly l && isPoly r
  | .forallBounded _ _ body => isPoly body
  | .existsBounded _ _ body => isPoly body
  | .divE l r => isPoly l && isPoly r
  | .abs e => isPoly e
  | .sqrt e => isPoly e
  | .isPrime _ => false
  | .divisorSum _ => false
  | .moebiusFn _ => false
  | .collatzReaches1 _ => false
  | .erdosStrausHolds _ => false
  | .fourSquares _ => false
  | .mertensBelow _ => false
  | .fltHolds _ => false
  | .primeCount _ => false
  | .goldbachRepCount _ => false
  | .primeGapMax _ => false
  | .intervalBound lo hi => isPoly lo && isPoly hi
  | .certifiedSum _ _ body => isPoly body

/-- Evaluate a polynomial formula for a specific binding. -/
def polyEval (env : Env) (e : Expr) : Bool := evalBool env e

/-- Polynomial decision with bounded evaluation.
    For invariants in the polynomial fragment, validity within a bounded range
    can be checked by evaluation. Soundness for the full ∀ statement requires
    an SOS certificate (generated by the Rust side). -/
def polyDecide (e : Expr) : Bool := isPoly e && evalBool (fun _ => 0) e

/-- Soundness of polyDecide. -/
theorem polyDecide_sound (e : Expr) (h : polyDecide e = true) :
    evalBool (fun _ => 0) e = true := by
  unfold polyDecide at h
  simp [Bool.and_eq_true] at h
  exact h.2

end KernelVm.Layers.Polynomial
